query Outlines {
  outlines {
    outlines {
      rootEntry {
        eid
        name
        expanded
        content
        rendered
        children {
          eid
          parentEid
          name
          expanded
          content
          rendered
        }
      }
    }
  }
}
