query Outline ($oid: Int!) {
  outline(oid: $oid) {
    name
    oid
    rootEntry {
      children {
        content
        eid
        expanded
        name
        parentEid
        rendered
      }
      content
      eid
      expanded
      name
      rendered
    }
  }
}
