query Outline ($oid: Int!) {
  outline(oid: $oid) {
    name
    oid
    rootEntry {
      eid
      name
      expanded
      content
      rendered
      children {
        eid
        parentEid
        name
        expanded
        content
        rendered
      }
    }
  }
}
