query Outlines {
  outlines {
    outlines {
      rootEntry {
        children {
          content
          name
          eid
          expanded
          rendered
          children {
            content
            name
            eid
            expanded
            rendered
          }
        }
        name
        eid
        expanded
        content
      }
    }
  }
}
