query Outlines {
  outlines {
    outlines {
      rootEntry {
        children {
          content
          name
          eid
        }
        name
        eid
        content
      }
    }
  }
}
