query Outline {
  outline(oid: "outline_two") {
    name
    oid
    rootEntry {
      eid
      name
      expanded
      content
      rendered
      children {
        eid
        parentEid
        name
        expanded
        content
        rendered
      }
    }
  }
}
